#!/bin/bash
set -euf
# Caution: Snapshots are unstable
IMAGEBUILDER_URL="https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-ImageBuilder-ar71xx_generic-for-linux-x86_64.tar.bz2"
# IMAGEBUILDER_URL="https://downloads.openwrt.org/snapshots/trunk/ramips/generic/OpenWrt-ImageBuilder-ramips_rt305x-for-linux-x86_64.tar.bz2"

cd $(dirname $(readlink -f $0))
git submodule update --init
if [  -z "${1:-}"  ];then
    echo "usage: $0 PROFILE"
    echo
    HIDE_TRAITS="true" sh $(dirname $(readlink -f $0))/bin/available_profiles
    exit 1
fi
PROFILE=$1
if [ ! -e builder/Makefile ]; then
    wget $IMAGEBUILDER_URL -O- | tar xjf -
    mv OpenWrt-ImageBuilder-*-for-linux-x86_64 builder
    echo "Builder successfully downloaded"
else
    echo "Builder already installed, skipping download"
fi
echo
echo "copying generic init:"
cp --remove-destination  lib/init  builder/init
echo "  profile/init -> builder/init"
cp --remove-destination  lib/init_overlay  builder/init_overlay
echo "  profile/init_overlay -> builder/init_overlay"
[ -e builder/overlay ] && echo "removing old overlay" && rm -rf builder/overlay
echo
echo "copying profile:"
./copy_profile "$PROFILE"

if [ -e builder/overlay ];then
    echo
    echo "This profile also contains overlay data,"
    echo 'run `builder/init_overlay` to copy'
fi
