#!/bin/bash
IMAGE=${IMAGE:-openwrt-ar71xx-generic-tl-wr703n-v1-squashfs-factory.bin}
cd $(dirname $(readlink -f $0))
if [ -z "${1:-}" ];then
    echo "usage: $0 ADDRESS"
    echo 
    echo "ENVIRONMENT:"
    echo "    IMAGE    (currently $IMAGE)"

    exit 1
fi

IP=$1
cd builder/bin/ar71xx/

if [ -e "$IMAGE" ];then
    scp $IMAGE root@$IP:/tmp/firmware.bin
    ssh root@$IP "/sbin/mtd write /tmp/firmware.bin firmware \
        && /sbin/reboot"
else
    echo "cannot find ar71xx build, aborting"
    exit 1
fi
