#!/bin/bash

cd $(dirname $(readlink -f $0))
if [ ! -e Makefile ] ;then 
    echo "ImageBuilder not checked out yet"
    echo "try running ../prepare $$PROFILE"
    exit 1
fi

echo 
rm -r bin/ || echo "no bindir, skipping removal"
if [ -e ./custom_make ];then
    echo "Starting Custom Make"
    sh ./custom_make # 2>/dev/null | while read line; do
        # printf "."
    # done
else
    echo "No Custom Make Script exists, bailing out!"
    exit 1
fi

echo

FACTORY=$(find bin/ | grep -e "squashfs-factory.bin$" | head -n 1)
SYSUPGRADE=$(find bin/ | grep -e "squashfs-sysupgrade.bin$" | head -n 1)

if [ "$FACTORY" != "" ];
then
    cat << EOF
finished building 
You can use the following images:
    Factory       : $PWD/$FACTORY
    System Upgrade: $PWD/$SYSUPGRADE
EOF
else
    cat << EOF
It seems like the factory image has not been created, it could mean
that the image would be too big and does not fit into the tiny FLASH.

Observe the output above, fix, and retry building.
EOF
fi
